// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chatMessage.proto

/*
Package protogen is a generated protocol buffer package.

It is generated from these files:
	chatMessage.proto
	chatService.proto

It has these top-level messages:
	Room
	Messages
	Message
*/
package protogen

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Room struct {
	RoomId       string `protobuf:"bytes,1,opt,name=roomId" json:"roomId,omitempty"`
	UserId       string `protobuf:"bytes,2,opt,name=userId" json:"userId,omitempty"`
	Name         string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	PictureURL   string `protobuf:"bytes,4,opt,name=pictureURL" json:"pictureURL,omitempty"`
	Type         string `protobuf:"bytes,5,opt,name=type" json:"type,omitempty"`
	WebhookToken string `protobuf:"bytes,6,opt,name=WebhookToken" json:"WebhookToken,omitempty"`
	Created      int64  `protobuf:"varint,7,opt,name=created" json:"created,omitempty"`
	Modified     int64  `protobuf:"varint,8,opt,name=modified" json:"modified,omitempty"`
}

func (m *Room) Reset()                    { *m = Room{} }
func (m *Room) String() string            { return proto.CompactTextString(m) }
func (*Room) ProtoMessage()               {}
func (*Room) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Room) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

func (m *Room) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Room) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Room) GetPictureURL() string {
	if m != nil {
		return m.PictureURL
	}
	return ""
}

func (m *Room) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Room) GetWebhookToken() string {
	if m != nil {
		return m.WebhookToken
	}
	return ""
}

func (m *Room) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *Room) GetModified() int64 {
	if m != nil {
		return m.Modified
	}
	return 0
}

type Messages struct {
	AllCount int64      `protobuf:"varint,1,opt,name=allCount" json:"allCount,omitempty"`
	Limit    int32      `protobuf:"varint,2,opt,name=limit" json:"limit,omitempty"`
	Offset   int32      `protobuf:"varint,3,opt,name=offset" json:"offset,omitempty"`
	Order    string     `protobuf:"bytes,4,opt,name=order" json:"order,omitempty"`
	Messages []*Message `protobuf:"bytes,5,rep,name=messages" json:"messages,omitempty"`
}

func (m *Messages) Reset()                    { *m = Messages{} }
func (m *Messages) String() string            { return proto.CompactTextString(m) }
func (*Messages) ProtoMessage()               {}
func (*Messages) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Messages) GetAllCount() int64 {
	if m != nil {
		return m.AllCount
	}
	return 0
}

func (m *Messages) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *Messages) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *Messages) GetOrder() string {
	if m != nil {
		return m.Order
	}
	return ""
}

func (m *Messages) GetMessages() []*Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

type Message struct {
	RoomId       string `protobuf:"bytes,1,opt,name=roomId" json:"roomId,omitempty"`
	UserId       string `protobuf:"bytes,2,opt,name=userId" json:"userId,omitempty"`
	Type         string `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
	EventName    string `protobuf:"bytes,4,opt,name=eventName" json:"eventName,omitempty"`
	Text         string `protobuf:"bytes,5,opt,name=text" json:"text,omitempty"`
	WebhookToken string `protobuf:"bytes,6,opt,name=WebhookToken" json:"WebhookToken,omitempty"`
	Created      int64  `protobuf:"varint,7,opt,name=created" json:"created,omitempty"`
	Modified     int64  `protobuf:"varint,8,opt,name=modified" json:"modified,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Message) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

func (m *Message) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Message) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Message) GetEventName() string {
	if m != nil {
		return m.EventName
	}
	return ""
}

func (m *Message) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Message) GetWebhookToken() string {
	if m != nil {
		return m.WebhookToken
	}
	return ""
}

func (m *Message) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *Message) GetModified() int64 {
	if m != nil {
		return m.Modified
	}
	return 0
}

func init() {
	proto.RegisterType((*Room)(nil), "proto.Room")
	proto.RegisterType((*Messages)(nil), "proto.Messages")
	proto.RegisterType((*Message)(nil), "proto.Message")
}

func init() { proto.RegisterFile("chatMessage.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 319 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x91, 0xc1, 0x4a, 0xf3, 0x40,
	0x14, 0x85, 0xc9, 0x9f, 0xa6, 0x4d, 0xef, 0x2f, 0x82, 0x83, 0xc8, 0x20, 0x22, 0x25, 0xab, 0xe2,
	0xa2, 0x0b, 0x7d, 0x03, 0x5d, 0x15, 0xd4, 0xc5, 0xa0, 0x08, 0xee, 0xd2, 0xce, 0x6d, 0x1b, 0xda,
	0xc9, 0x2d, 0x93, 0x89, 0xd4, 0x17, 0xf1, 0xd9, 0xf4, 0x6d, 0x64, 0xee, 0x8c, 0xb1, 0x6e, 0x05,
	0x57, 0xb9, 0xdf, 0x39, 0x73, 0xc9, 0x9c, 0x33, 0x70, 0x34, 0x5f, 0x95, 0xee, 0x0e, 0x9b, 0xa6,
	0x5c, 0xe2, 0x64, 0x6b, 0xc9, 0x91, 0xc8, 0xf8, 0x53, 0xbc, 0x27, 0xd0, 0x53, 0x44, 0x46, 0x9c,
	0x40, 0xdf, 0x12, 0x99, 0xa9, 0x96, 0xc9, 0x28, 0x19, 0x0f, 0x55, 0x24, 0xaf, 0xb7, 0x0d, 0xda,
	0xa9, 0x96, 0xff, 0x82, 0x1e, 0x48, 0x08, 0xe8, 0xd5, 0xa5, 0x41, 0x99, 0xb2, 0xca, 0xb3, 0x38,
	0x07, 0xd8, 0x56, 0x73, 0xd7, 0x5a, 0x7c, 0x54, 0xb7, 0xb2, 0xc7, 0xce, 0x9e, 0xe2, 0x77, 0xdc,
	0xeb, 0x16, 0x65, 0x16, 0x76, 0xfc, 0x2c, 0x0a, 0x38, 0x78, 0xc2, 0xd9, 0x8a, 0x68, 0xfd, 0x40,
	0x6b, 0xac, 0x65, 0x9f, 0xbd, 0x1f, 0x9a, 0x90, 0x30, 0x98, 0x5b, 0x2c, 0x1d, 0x6a, 0x39, 0x18,
	0x25, 0xe3, 0x54, 0x7d, 0xa1, 0x38, 0x85, 0xdc, 0x90, 0xae, 0x16, 0x15, 0x6a, 0x99, 0xb3, 0xd5,
	0x71, 0xf1, 0x96, 0x40, 0x1e, 0x33, 0x37, 0xfe, 0x60, 0xb9, 0xd9, 0xdc, 0x50, 0x5b, 0x3b, 0x0e,
	0x98, 0xaa, 0x8e, 0xc5, 0x31, 0x64, 0x9b, 0xca, 0x54, 0x8e, 0x13, 0x66, 0x2a, 0x80, 0x0f, 0x4e,
	0x8b, 0x45, 0x83, 0x8e, 0x23, 0x66, 0x2a, 0x92, 0x3f, 0x4d, 0x56, 0xa3, 0x8d, 0xf9, 0x02, 0x88,
	0x0b, 0xc8, 0x4d, 0xfc, 0x97, 0xcc, 0x46, 0xe9, 0xf8, 0xff, 0xe5, 0x61, 0x28, 0x7a, 0x12, 0xaf,
	0xa0, 0x3a, 0xbf, 0xf8, 0x48, 0x60, 0x10, 0xd5, 0xdf, 0xd4, 0xce, 0x15, 0xa6, 0x7b, 0x15, 0x9e,
	0xc1, 0x10, 0x5f, 0xb0, 0x76, 0xf7, 0xfe, 0x3d, 0xc2, 0xad, 0xbe, 0x05, 0xde, 0xc0, 0x9d, 0xeb,
	0x4a, 0xc7, 0x9d, 0xfb, 0xbb, 0xd2, 0xaf, 0xe1, 0x39, 0xe7, 0xd8, 0x4b, 0xac, 0x67, 0x7d, 0x9e,
	0xae, 0x3e, 0x03, 0x00, 0x00, 0xff, 0xff, 0x90, 0x8f, 0xb7, 0xc3, 0x7e, 0x02, 0x00, 0x00,
}
